name: mobile_drs_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^5.8.2
  crypto: ^3.0.6
  provider: ^6.1.4
  permission_handler: ^12.0.0+1
  network_info_plus: ^6.1.3
  camera: ^0.11.1
  video_player: ^2.9.5
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
