name: mobile_drs_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  arcore_flutter_plugin:
    git:
      url: https://github.com/giandifra/arcore_flutter_plugin.git
  vector_math: ^2.1.4
  sensors_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
