name: mobile_drs_system
description: "An application for umpires to get DRS reviews and decisions."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  sensors_plus: ^6.1.1
  geolocator: ^10.0.0
  basic_utils: ^5.8.2
  crypto: ^3.0.6
  provider: ^6.1.4
  permission_handler: ^11.3.1
  network_info_plus: ^6.1.3
  camera: ^0.11.1
  video_player: ^2.9.5
  path: ^1.9.1
  flutter_media_store: ^1.3.1
  flutter_native_splash: ^2.4.6
  path_provider: ^2.0.14
  file_picker: ^10.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_bg.jpg
    - assets/black.jpg
